name: angular_router
repository: https://github.com/dart-lang/angular
description: Router for AngularDart.
version: 2.0.0-dev

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  angular:
    git:
      url: https://github.com/dart-lang/angular
      ref: master
      path: angular
  collection: ^1.14.5
  js: ^0.6.0
  meta: ^1.1.4

dev_dependencies:
  async: ^2.0.3
  angular_test:
    git:
      url: https://github.com/dzolotov/angular
      ref: master
      path: angular_test
  build_runner: ^1.0.0
  build_test: ^1.0.0
  build_web_compilers: ^2.0.0
  mockito: ^3.0.0-alpha
  pedantic: ^1.2.0
  test: ^1.3.0

# === vvv REMOVE WHEN PUBLISHING vvv ===
dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
  angular_test:
    path: ../angular_test
# === ^^^ REMOVE WHEN PUBLISHING ^^^ ===
